version: '3'

services:
  boolsim-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: boolsim-mcp
    ports:
      - "3050:3050"
    restart: unless-stopped
    volumes:
      # For development, you can uncomment the following lines to mount the source code
      # - ./src:/app/src
      # For logs persistence
      - ./logs:/app/logs
    environment:
      - NODE_ENV=production
      - PORT=3050
    networks:
      - boolsim-network
    # Important: Make sure the boolSim tar file is in the ./boolSim directory
    # before building the container

networks:
  boolsim-network:
    driver: bridge 