version: '3.8'

services:
  postgres:
    ports:
      - "3003:5432"
  
  backend:
    ports:
      - "3002:3000"
    environment:
      - PORT=3000
  
  frontend:
    ports:
      - "3001:80"
    environment:
      - REACT_APP_API_URL=http://localhost:3002
