version: '3.8'

services:
  weather-mcp:
    build:
      context: ./mcp-servers
      dockerfile: Dockerfile
    image: weather-mcp-server:latest
    container_name: weather-mcp-server
    ports:
      - "3100:3100"
    volumes:
      - ./mcp-servers/logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3100"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s 